import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Search from '@/components/Search'
import MainSection from '@/components/MainSection'

import 'swiper/css';
import MainSecondSection from '@/components/MainSecondSection'

export default function Home() {
  return (
    <>
      <Head>
        <title>Booklip</title>
        <meta name="description" content="Generated by JEI" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainSection />
        <MainSecondSection />
      </main>
    </>
  )
}
